name: JS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - uses: flarum/action-build@3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: yarn
